apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eloy83-eloy83-poi-map-app-dev
  annotations:
    argocd/app-name: eloy83-eloy83-poi-map-app-dev
    backstage.io/kubernetes-id: eloy83-eloy83-poi-map-app-dev
    backstage.io/kubernetes-namespace: eloy83
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=eloy83-eloy83-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/eloy83-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/eloy83/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/eloy83/deployments/eloy83-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/eloy83-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://eloy83-poi-map-app-eloy83.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "name:default/eloy83"
  system: workshop-system-eloy83
  consumesApis:
    - gateway-api-eloy83
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-eloy83
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "name:default/eloy83"
